"use client";
import { useMemo, useState } from "react";
import { useAccount, useConnect, useDisconnect, useSwitchChain, usePublicClient, useWalletClient } from "wagmi";
import { sepolia } from "wagmi/chains";
import { ShieldCheck, Upload, LockKeyhole, Users, WalletCards, CheckCircle2, ExternalLink, ArrowRight, FileSpreadsheet } from "lucide-react";
import { getFheAirdropFactoryAddress, getFheDisperseSingletonAddress, getFheVestingFactoryAddress } from "@tokenops/sdk";
import { createSepoliaEncryptorWeb, setOperator } from "@tokenops/sdk/fhe";
import { createConfidentialAirdropClient, createConfidentialAirdropFactoryClient, encryptUint64, signClaimAuthorization } from "@tokenops/sdk/fhe-airdrop";
import { createConfidentialDisperseClient } from "@tokenops/sdk/fhe-disperse";
import { createConfidentialVestingFactoryClient, createConfidentialVestingManagerClient } from "@tokenops/sdk/fhe-vesting";
import { isAddress, keccak256, parseUnits, stringToHex, type Address } from "viem";

const flows = [
  ["Airdrop", "Signed private claims", "airdrop"], ["Vesting", "Cliffs and unlocks", "vesting"], ["Payroll", "Recurring contributor pay", "disperse"], ["Grants", "Private award batches", "disperse"],
  ["Referrals", "Hidden earned rewards", "disperse"], ["Team", "Confidential team schedules", "vesting"], ["Investors", "Private investor unlocks", "vesting"], ["Disperse", "One transaction, many recipients", "disperse"]
] as const;

export function ShadowApp() {
  const { address, isConnected, chainId } = useAccount(); const { connect, connectors } = useConnect(); const { disconnect } = useDisconnect(); const { switchChain } = useSwitchChain();
  const publicClient=usePublicClient(); const {data:walletClient}=useWalletClient();
  const [selected, setSelected] = useState("Airdrop"); const [rows, setRows] = useState<{address:string; amount:string}[]>([]); const [name, setName] = useState("Genesis Community Drop"); const[token,setToken]=useState(""); const[status,setStatus]=useState("Ready for encrypted input"); const[busy,setBusy]=useState(false);const[claim,setClaim]=useState<{airdrop:Address;recipient:Address;handle:`0x${string}`;inputProof:`0x${string}`;signature:`0x${string}`}|null>(null);
  const addresses = useMemo(() => ({ airdrop: getFheAirdropFactoryAddress(sepolia.id), vesting: getFheVestingFactoryAddress(sepolia.id), disperse: getFheDisperseSingletonAddress(sepolia.id) }), []);
  const flow = flows.find(([label]) => label === selected)!;
  function readCsv(file?: File) { if (!file) return; const reader = new FileReader(); reader.onload = () => { const parsed = String(reader.result).split(/\r?\n/).slice(1).map(line => line.split(",")).filter(x => /^0x[a-fA-F0-9]{40}$/.test(x[0]?.trim()) && Number(x[1]) > 0).map(x => ({address:x[0].trim(), amount:x[1].trim()})); setRows(parsed); }; reader.readAsText(file); }
  const total = rows.reduce((n,r)=>n+Number(r.amount),0);
  async function execute(){if(!address||!publicClient||!walletClient||!isAddress(token)||rows.length===0)return;setBusy(true);let encryptor:Awaited<ReturnType<typeof createSepoliaEncryptorWeb>>|undefined;try{setStatus("Initializing Zama relayer…");encryptor=await createSepoliaEncryptorWeb({publicClient,walletClient});const tokenAddress=token as Address;const salt=keccak256(stringToHex(`${name}:${address}:${Date.now()}`));const now=Math.floor(Date.now()/1000);
    if(flow[2]==="airdrop"){const spender=addresses.airdrop!;setStatus("Approving TokenOps airdrop factory…");await setOperator({publicClient,walletClient,token:tokenAddress,spender,account:address,deadline:BigInt(now+86400*45)});const client=createConfidentialAirdropFactoryClient({publicClient,walletClient,encryptor});setStatus("Encrypting and funding airdrop…");const result=await client.createAndFundConfidentialAirdrop({params:{token:tokenAddress,startTimestamp:now,endTimestamp:now+86400*30,canExtendClaimWindow:true,admin:address},userSalt:salt,amount:parseUnits(String(total),6),account:address});setStatus("Generating recipient-bound claim authorizations…");const payloads=[];for(const row of rows){const recipient=row.address as Address;const encryptedInput=await encryptUint64({encryptor,contractAddress:result.airdrop,userAddress:recipient,value:parseUnits(row.amount,6)});const signature=await signClaimAuthorization({walletClient,airdropAddress:result.airdrop,recipient,encryptedAmountHandle:encryptedInput.handle});payloads.push({airdrop:result.airdrop,recipient,...encryptedInput,signature})}const blob=new Blob([JSON.stringify({version:1,campaign:name,chainId:sepolia.id,claims:payloads},null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`${name.toLowerCase().replace(/[^a-z0-9]+/g,"-")}-private-claims.json`;a.click();URL.revokeObjectURL(url);setStatus(`Airdrop live · ${result.airdrop.slice(0,10)}… · authorizations downloaded`);
    }else if(flow[2]==="vesting"){const factory=createConfidentialVestingFactoryClient({publicClient,walletClient});setStatus("Deploying confidential vesting manager…");const deployed=await factory.createManager({token:tokenAddress,userSalt:salt,splitEnabled:true,pausableEnabled:true,account:address});setStatus("Approving vesting manager…");await setOperator({publicClient,walletClient,token:tokenAddress,spender:deployed.manager,account:address,deadline:BigInt(now+86400*365*3)});const manager=createConfidentialVestingManagerClient({publicClient,walletClient,address:deployed.manager,encryptor});setStatus("Encrypting vesting schedules…");await manager.batchCreateVesting({items:rows.map(row=>({params:{recipient:row.address as Address,startTimestamp:now,endTimestamp:now+86400*365,cliffSeconds:86400*30,releaseIntervalSecs:86400*30,timelockSeconds:0,initialUnlockBps:0,cliffAmountBps:0,isRevocable:true},amount:parseUnits(row.amount,6)})),account:address});setStatus(`Vesting live · ${deployed.manager.slice(0,10)}…`);
    }else{const spender=addresses.disperse!;setStatus("Approving confidential disperse singleton…");await setOperator({publicClient,walletClient,token:tokenAddress,spender,account:address,deadline:BigInt(now+86400)});const client=createConfidentialDisperseClient({publicClient,walletClient,encryptor});setStatus("Encrypting recipient batch…");const result=await client.disperse({token:tokenAddress,mode:"direct",recipients:rows.map(r=>r.address as Address),amounts:rows.map(r=>parseUnits(r.amount,6)),account:address});setStatus(`Distribution confirmed · ${result.hash.slice(0,10)}…`)}
  }catch(e){setStatus(e instanceof Error?e.message:"Operation failed")}finally{encryptor?.terminate();setBusy(false)}}
  async function claimAllocation(){if(!claim||!address||!publicClient||!walletClient)return;if(claim.recipient.toLowerCase()!==address.toLowerCase()){setStatus("Connected wallet is not this claim recipient");return}setBusy(true);try{const client=createConfidentialAirdropClient({publicClient,walletClient,address:claim.airdrop});setStatus("Validating private authorization…");const valid=await client.isSignatureValid({encryptedAmountHandle:claim.handle,signature:claim.signature,caller:address});if(!valid)throw new Error("Claim authorization is invalid or already used");setStatus("Submitting confidential claim…");const hash=await client.claim({encryptedInput:{handle:claim.handle,inputProof:claim.inputProof},signature:claim.signature,account:address});setStatus(`Claim confirmed · ${hash.slice(0,10)}…`)}catch(e){setStatus(e instanceof Error?e.message:"Claim failed")}finally{setBusy(false)}}
  function readClaim(file?:File){if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const json=JSON.parse(String(reader.result));const found=(json.claims||[json]).find((item:{recipient:string})=>item.recipient?.toLowerCase()===address?.toLowerCase());if(!found)throw new Error("No authorization for connected wallet");setClaim({airdrop:found.airdrop,recipient:found.recipient,handle:found.handle,inputProof:found.inputProof,signature:found.signature});setStatus("Private claim authorization loaded")}catch(e){setStatus(e instanceof Error?e.message:"Invalid claim file")}};reader.readAsText(file)}
  return <main>
    <nav><div className="brand"><span className="mark"><LockKeyhole size={18}/></span>SHADOWDROP</div><div className="navmeta"><span className="network">● SEPOLIA</span>{isConnected ? <button className="wallet" onClick={()=>disconnect()}>{address?.slice(0,6)}…{address?.slice(-4)}</button> : <button className="wallet" onClick={()=>connect({connector:connectors[0]})}>Connect wallet</button>}</div></nav>
    <section className="hero"><div><div className="eyebrow">CONFIDENTIAL TOKEN OPERATIONS</div><h1>Distribute value.<br/><em>Reveal nothing.</em></h1><p>Institution-grade airdrops, vesting, payroll, grants and rewards powered by Zama FHE and TokenOps.</p><div className="proof"><span><ShieldCheck/> Encrypted onchain</span><span><Users/> Recipient-only access</span><span><WalletCards/> ERC-7984</span></div></div><div className="heroCard"><div className="pulse"/><small>PRIVATE DISTRIBUTION</small><strong>8 operational flows</strong><p>Amounts are encrypted before they leave this browser. ShadowDrop never receives plaintext allocations.</p><a href="#workspace">Open console <ArrowRight size={15}/></a></div></section>
    <section id="workspace" className="workspace"><aside><div className="asideTitle">OPERATIONS</div>{flows.map(([label,desc])=><button key={label} className={selected===label?"flow active":"flow"} onClick={()=>{setSelected(label);setRows([])}}><span>{label}</span><small>{desc}</small></button>)}</aside>
      <div className="console"><div className="consoleHead"><div><div className="eyebrow">NEW OPERATION / {selected.toUpperCase()}</div><h2>{selected} console</h2></div><span className="sdk">TOKENOPS SDK 1.0</span></div>
        {chainId && chainId!==sepolia.id && <button className="warning" onClick={()=>switchChain({chainId:sepolia.id})}>Switch to Ethereum Sepolia</button>}
        <div className="formGrid"><label>Campaign name<input value={name} onChange={e=>setName(e.target.value)} /></label><label>ERC-7984 token<input value={token} onChange={e=>setToken(e.target.value)} placeholder="0x confidential token"/></label></div><label className="contractLine">Execution contract <code>{addresses[flow[2]] || "Unavailable"}</code></label>
        <div className="drop"><FileSpreadsheet size={28}/><strong>Import encrypted allocation batch</strong><p>CSV columns: address, amount. Validation and encryption happen locally.</p><label className="upload"><Upload size={15}/> Select CSV<input type="file" accept=".csv,text/csv" onChange={e=>readCsv(e.target.files?.[0])}/></label></div>
        <div className="summary"><div><small>VALID RECIPIENTS</small><strong>{rows.length}</strong></div><div><small>LOCAL TOTAL</small><strong>{total.toLocaleString()}</strong></div><div><small>PUBLIC AMOUNTS</small><strong className="safe">0</strong></div></div>
        {rows.length>0 && <div className="preview">{rows.slice(0,4).map((r,i)=><div key={r.address}><span>{String(i+1).padStart(2,"0")}</span><code>{r.address.slice(0,10)}…{r.address.slice(-6)}</code><b>••••••</b><CheckCircle2 size={16}/></div>)}</div>}
        <div className="actionRow"><div><b>{status}</b><small>Validate → encrypt → simulate → sign → confirm → ACL ready</small></div><button disabled={!isConnected||rows.length===0||!isAddress(token)||busy} onClick={execute}>{busy?"Processing…":"Execute privately"} <ArrowRight size={16}/></button></div>
      </div>
    </section>
    <section className="claimCenter"><div><div className="eyebrow">RECIPIENT CLAIM CENTER</div><h2>Claim without exposing the amount.</h2><p>Import the private authorization file supplied by the issuer. ShadowDrop selects only the record bound to your connected wallet.</p></div><div className="claimBox"><label className="upload"><Upload size={15}/> Import authorization<input type="file" accept="application/json" onChange={e=>readClaim(e.target.files?.[0])}/></label><div><small>AUTHORIZATION</small><b>{claim?`${claim.airdrop.slice(0,10)}… ready`:"Not loaded"}</b></div><button disabled={!claim||busy||!isConnected} onClick={claimAllocation}>Validate & claim <ArrowRight size={16}/></button></div></section>
    <section className="contracts"><div><div className="eyebrow">VERIFIABLE INFRASTRUCTURE</div><h2>Live TokenOps on Sepolia</h2></div>{Object.entries(addresses).map(([k,v])=><a key={k} href={`https://sepolia.etherscan.io/address/${v}`} target="_blank"><span>{k}</span><code>{v}</code><ExternalLink size={15}/></a>)}</section>
    <footer><div className="brand">SHADOWDROP</div><p>Privacy protects values, not wallet identity. Never upload sensitive plaintext data.</p><span>Built with Zama × TokenOps</span></footer>
  </main>;
}
